apps/funcionarios/urls.py
from django.urls import path
from .views import (FuncionariosList,
                    FuncionariosEdit,
                    FuncionariosDelete,
                    FuncionariosCreate,
                    FuncionariosRelatorioPdf,
                    FuncionariosRelatorioMock,
                    )

urlpatterns = [
    path('', FuncionariosList.as_view(), name='listar_funcionarios'),
    path('editar/<int:pk>/', FuncionariosEdit.as_view(), name='editar_funcionarios'),
    path('deletar/<int:pk>/', FuncionariosDelete.as_view(), name='deletar_funcionarios'),
    path('novo/', FuncionariosCreate.as_view(), name='criar_funcionarios'),
    path('relatorio/pdf/', FuncionariosRelatorioPdf.as_view(), name='gerar_pdf_funcionarios'),
    path('relatorio/pdf/mock/', FuncionariosRelatorioMock.as_view(), name='gerar_pdf_funcionarios_mock'),
]

gestao_rh/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.decorators.cache import cache_control
from django.views.static import serve

urlpatterns = [
    path('', include('apps.core.urls')),
    path('funcionarios/', include('apps.funcionarios.urls')),
    path('empresas/', include('apps.empresas.urls')),
    path('departamentos/', include('apps.departamentos.urls')),
    path('documentos/', include('apps.documentos.urls')),
    path('hora-extra/', include('apps.registro_hora_extra.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.STATIC_URL, view=cache_control(no_cache=True, must_revalidate=True)(serve))
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns += staticfiles_urlpatterns()

apps/documentos/models.py
from django.db import models
from django.urls import reverse

from apps.funcionarios.models import Funcionario


class Documento(models.Model):
    descricao = models.CharField(max_length=100)
    arquivo = models.FileField(upload_to='documentos')
    pertence = models.ForeignKey(Funcionario, on_delete=models.deletion.PROTECT)

    def __str__(self):
        return self.descricao

    def get_absolute_url(self):
        return reverse('editar_funcionarios', args=[self.pertence.id])

apps/funcionarios/models.py
from decimal import Decimal

from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum
from django.urls import reverse
from apps.departamentos.models import Departamento
from apps.empresas.models import Empresa


class Funcionario(models.Model):
    nome = models.CharField(max_length=100)
    user = models.OneToOneField(User, on_delete=models.deletion.PROTECT)
    departamentos = models.ManyToManyField(Departamento)
    empresa = models.ForeignKey(Empresa, on_delete=models.deletion.PROTECT,
                                null=True, blank=True)

    def __str__(self):
        return self.nome

    def get_absolute_url(self):
        return reverse('listar_funcionarios')

    @property
    def total_horas_extras(self):
        return self.registrohoraextra_set \
                        .filter(utilizada=False) \
                        .aggregate(Sum('hora_extra'))['hora_extra__sum'] or 0

apps/registro_hora_extra/models.py
from django.db import models
from django.urls import reverse

from apps.funcionarios.models import Funcionario


class RegistroHoraExtra(models.Model):
    motivo = models.CharField(max_length=100)
    funcionario = models.ForeignKey(Funcionario, on_delete=models.deletion.PROTECT)
    hora_extra = models.DecimalField(max_digits=5, decimal_places=2)
    utilizada = models.BooleanField(default=False)

    def __str__(self):
        return self.motivo

apps/funcionarios/views.py
import itertools

from django.contrib.auth.models import User
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView
from django.views.generic.edit import UpdateView, DeleteView, CreateView
from .models import Funcionario
from .render import Render


class FuncionariosList(ListView):
    model = Funcionario

    def get_queryset(self):
        empresa_logada = self.request.user.funcionario.empresa
        queryset = Funcionario.objects.filter(empresa=empresa_logada)
        return queryset


class FuncionariosEdit(UpdateView):
    model = Funcionario
    fields = ['nome','departamentos']


class FuncionariosDelete(DeleteView):
    model = Funcionario
    success_url = reverse_lazy('listar_funcionarios')


class FuncionariosCreate(CreateView):
    model = Funcionario
    fields = ['nome', 'departamentos']

    def form_valid(self, form):
        funcionario = form.save(commit=False)
        funcionario.empresa = self.request.user.funcionario.empresa
        nome_funcionario = ''.join(nome.capitalize() for nome in itertools.islice(funcionario.nome.split(' '), 0, 2))
        funcionario.user = User.objects.create(username=nome_funcionario)
        funcionario.save()
        return super(FuncionariosCreate, self).form_valid(form)

class FuncionariosRelatorioPdf(View):

    def get(self, *args, **kwargs):
        funcionarios = Funcionario.objects.filter(empresa=self.request.user.funcionario.empresa)
        params = {'funcionarios': funcionarios}
        return Render.render('funcionarios/relatorio-pdf.html', params, 'RelatorioFuncionario')

class FuncionariosRelatorioMock(View):

    def get(self, *args, **kwargs):
        funcionarios = Funcionario.objects.filter(empresa=self.request.user.funcionario.empresa)
        params = {'funcionarios':funcionarios}
        return render(self.request, 'funcionarios/relatorio-pdf.html', params)

apps/funcionarios/templates/funcionarios/funcionario_confirm_delete.html
{% extends 'base.html' %}

{% load bootstrap %}
{% block main %}
    <form method="post" class="form-control">
        {% csrf_token %}
        <h1> Voce esta certo que quer <b>deletar</b> {{ obj }}</h1>
        {{ form|bootstrap }}

        <button type="submit" class="btn btn-danger" href="">Confirmar</button>
        <a href="{% url 'listar_funcionarios' %}" class="btn btn-info">Cancelar</a>
    </form>

{% endblock %}

apps/funcionarios/templates/funcionarios/funcionario_form.html
{% extends 'base.html' %}

{% load bootstrap %}
{% block main %}
    <form method="post">
        {% csrf_token %}
        {{ form|bootstrap }}
        <button type="submit" class="btn btn-info">Salvar</button>
    </form>
    {% if object.id %}
        <h2>Documentos</h2>
        <ul>
            {% for documento in object.documento_set.all %}
                <li><a href="{{ documento.arquivo.url }}">{{ documento }}</a></li>
                {% empty %}
                <li> Nenhum Documento Anexado. </li>
            {% endfor %}
        </ul>
        <a href="{% url 'criar_documentos' object.id %}" class="btn btn-success mt-1" >Adicionar Documentos</a>
        <h2>Registro de Banco de Horas</h2>
        <ul>
            {% for registro in object.registrohoraextra_set.all %}
                <li><a href="{% url 'editar_hora_extra_por_funcionario' pk=registro.id funcionario_id=object.id %}">{{ registro }}</a> - {{ registro.hora_extra }}</li>
                {% empty %}
                <li> Nenhum Documento Anexado. </li>
            {% endfor %}
        </ul>
        <h4>Total Hora Extra: {{ object.total_horas_extras }}</h4>
        <a href="{% url 'criar_hora_extra_por_funcionario' object.id  %}" class="btn btn-success mt-1" >Adicionar Hora Extra</a>
    {% endif %}
{% endblock %}

apps/funcionarios/templates/funcionarios/funcionario_list.html
{% extends 'base.html' %}

{% block main %}

    {% for funcionario in object_list %}
    <div class="row">
        <div class="col-sm-auto"><a href="{% url 'editar_funcionarios' funcionario.id %}">Editar </a></div>
        <div class="col-sm-auto"><a href="{% url 'deletar_funcionarios' funcionario.id %}">Deletar </a></div>
        <div class="col-lg">{{ funcionario }}</div>


    </div>
    {% endfor %}
    <a href="{% url 'criar_funcionarios' %}" class="btn btn-info"> Criar Funcionario</a>
    {% if object_list %}
        <a href="{% url 'gerar_pdf_funcionarios' %}" class="btn btn-light">Gerar Relatorios</a>
    {% endif %}
{% endblock %}

apps/funcionarios/templates/funcionarios/relatorio-pdf.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap %}


{% block main %}
    <h2> Relatorio funcionario</h2>
    <table class="table table-responsive table-striped">
        <thead class="table-dark">
        <tr>
            <th scope="col">Nome Funcionario</th>
            <th scope="col">Total Hora Extra</th>
        </tr>
        </thead>
        <tbody class="tab-content">
        {% for func in funcionarios %}
            <tr scope="col"><td>{{ func }}</td><td>{{ func.total_horas_extras }}</td></tr>
        {% endfor %}
        </tbody>
    </table>
    <button type="button" class="btn btn-info"> teste de css </button>
{% endblock %}